apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "ebs-sc" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  labels:
    proj: expense
spec:
  volumes:
    - name: ebs-dynamic
      persistentVolumeClaim:
        claimName: ebs-dynamic
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: ebs-dynamic
---
apiVersion: v1 
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  selector:
   proj: expense
  ports:
  - name: expense
    protocol: TCP
    port: 80
    targetPort: 80 
    nodePort: 30000
