apiVersion: v1
kind: Pod
metadata:
  name: expense2
  labels:
    namespace: expense
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx  
  - name: alpine
    image: alpine
    command: ["sleep", "1000"]