apiVersion: v1 
kind: Pod
metadata:
  name: config-pod
spec: 
  containers:
  - name: nginx
    image: nginx
    # env: 
    # - name: author
    #   valueFrom:
    #      configMapKeyRef:
    #       name: configs
    #       key: author
    envFrom:
      - configMapRef:
          name: configs